export const GBC_AUDIO_MAP: Record<string, string> = {
  gen: "Genesis", exo: "Exodus", lev: "Leviticus", num: "Numbers", deu: "Deuteronomy",
  jos: "Joshua", jdg: "Judges", rut: "Ruth",
  "1sa": "I_Samuel", "2sa": "II_Samuel", "1ki": "I_Kings", "2ki": "II_Kings",
  "1ch": "I_Chronicles", "2ch": "II_Chronicles", ezr: "Ezra", neh: "Nehemiah", est: "Esther",
  job: "Job", psa: "Psalms", pro: "Proverbs", ecc: "Ecclesiastes", sos: "Song_of_Solomon",
  isa: "Isaiah", jer: "Jeremiah", lam: "Lamentations", eze: "Ezekiel", dan: "Daniel",
  hos: "Hosea", jol: "Joel", amo: "Amos", oba: "Obadiah", jon: "Jonah",
  mic: "Micah", nah: "Nahum", hab: "Habakkuk", zep: "Zephaniah", hag: "Haggai",
  zec: "Zechariah", mal: "Malachi",
  mat: "Mathew", mrk: "Mark", luk: "Luke", jhn: "John", act: "Acts",
  rom: "Romans", "1co": "I_Corinthians", "2co": "II_Corinthians", gal: "Galatians", eph: "Ephesians",
  php: "Philippians", col: "Colossians", "1th": "I_Thessalonians", "2th": "II_Thessalonians",
  "1ti": "I_Timothy", "2ti": "II_Timothy", tit: "Titus", phm: "Philemon", heb: "Hebrews",
  jas: "James", "1pe": "I_Peter", "2pe": "II_Peter", "1jn": "I_John", "2jn": "II_John",
  "3jn": "III_John", jud: "Jude", rev: "Revelation",
};

export const bibleBooks = [
  { id: "gen", name: "Genesis", nameUrdu: "پیدائش", chapters: 50, testament: "old" },
  { id: "exo", name: "Exodus", nameUrdu: "خروج", chapters: 40, testament: "old" },
  { id: "lev", name: "Leviticus", nameUrdu: "احبار", chapters: 27, testament: "old" },
  { id: "num", name: "Numbers", nameUrdu: "گنتی", chapters: 36, testament: "old" },
  { id: "deu", name: "Deuteronomy", nameUrdu: "استثنا", chapters: 34, testament: "old" },
  { id: "jos", name: "Joshua", nameUrdu: "یوشع", chapters: 24, testament: "old" },
  { id: "jdg", name: "Judges", nameUrdu: "قضات", chapters: 21, testament: "old" },
  { id: "rut", name: "Ruth", nameUrdu: "روت", chapters: 4, testament: "old" },
  { id: "1sa", name: "1 Samuel", nameUrdu: "1 سموئیل", chapters: 31, testament: "old" },
  { id: "2sa", name: "2 Samuel", nameUrdu: "2 سموئیل", chapters: 24, testament: "old" },
  { id: "1ki", name: "1 Kings", nameUrdu: "1 سلاطین", chapters: 22, testament: "old" },
  { id: "2ki", name: "2 Kings", nameUrdu: "2 سلاطین", chapters: 25, testament: "old" },
  { id: "1ch", name: "1 Chronicles", nameUrdu: "1 تواریخ", chapters: 29, testament: "old" },
  { id: "2ch", name: "2 Chronicles", nameUrdu: "2 تواریخ", chapters: 36, testament: "old" },
  { id: "ezr", name: "Ezra", nameUrdu: "عزرا", chapters: 10, testament: "old" },
  { id: "neh", name: "Nehemiah", nameUrdu: "نحمیاہ", chapters: 13, testament: "old" },
  { id: "est", name: "Esther", nameUrdu: "استر", chapters: 10, testament: "old" },
  { id: "job", name: "Job", nameUrdu: "ایوب", chapters: 42, testament: "old" },
  { id: "psa", name: "Psalms", nameUrdu: "زبور", chapters: 150, testament: "old" },
  { id: "pro", name: "Proverbs", nameUrdu: "امثال", chapters: 31, testament: "old" },
  { id: "ecc", name: "Ecclesiastes", nameUrdu: "واعظ", chapters: 12, testament: "old" },
  { id: "sos", name: "Song of Solomon", nameUrdu: "غزل غزلات", chapters: 8, testament: "old" },
  { id: "isa", name: "Isaiah", nameUrdu: "یسعیاہ", chapters: 66, testament: "old" },
  { id: "jer", name: "Jeremiah", nameUrdu: "یرمیاہ", chapters: 52, testament: "old" },
  { id: "lam", name: "Lamentations", nameUrdu: "مراثی", chapters: 5, testament: "old" },
  { id: "eze", name: "Ezekiel", nameUrdu: "حزقی ایل", chapters: 48, testament: "old" },
  { id: "dan", name: "Daniel", nameUrdu: "دانی ایل", chapters: 12, testament: "old" },
  { id: "hos", name: "Hosea", nameUrdu: "ہوشع", chapters: 14, testament: "old" },
  { id: "jol", name: "Joel", nameUrdu: "یوایل", chapters: 3, testament: "old" },
  { id: "amo", name: "Amos", nameUrdu: "عاموس", chapters: 9, testament: "old" },
  { id: "oba", name: "Obadiah", nameUrdu: "عوبدیہ", chapters: 1, testament: "old" },
  { id: "jon", name: "Jonah", nameUrdu: "یونس", chapters: 4, testament: "old" },
  { id: "mic", name: "Micah", nameUrdu: "میکاہ", chapters: 7, testament: "old" },
  { id: "nah", name: "Nahum", nameUrdu: "ناحوم", chapters: 3, testament: "old" },
  { id: "hab", name: "Habakkuk", nameUrdu: "حبقوق", chapters: 3, testament: "old" },
  { id: "zep", name: "Zephaniah", nameUrdu: "صفنیاہ", chapters: 3, testament: "old" },
  { id: "hag", name: "Haggai", nameUrdu: "حجی", chapters: 2, testament: "old" },
  { id: "zec", name: "Zechariah", nameUrdu: "زکریاہ", chapters: 14, testament: "old" },
  { id: "mal", name: "Malachi", nameUrdu: "ملاکی", chapters: 4, testament: "old" },
  { id: "mat", name: "Matthew", nameUrdu: "متی", chapters: 28, testament: "new" },
  { id: "mrk", name: "Mark", nameUrdu: "مرقس", chapters: 16, testament: "new" },
  { id: "luk", name: "Luke", nameUrdu: "لوقا", chapters: 24, testament: "new" },
  { id: "jhn", name: "John", nameUrdu: "یوحنا", chapters: 21, testament: "new" },
  { id: "act", name: "Acts", nameUrdu: "اعمال", chapters: 28, testament: "new" },
  { id: "rom", name: "Romans", nameUrdu: "رومیوں", chapters: 16, testament: "new" },
  { id: "1co", name: "1 Corinthians", nameUrdu: "1 کرنتھیوں", chapters: 16, testament: "new" },
  { id: "2co", name: "2 Corinthians", nameUrdu: "2 کرنتھیوں", chapters: 13, testament: "new" },
  { id: "gal", name: "Galatians", nameUrdu: "گلاتیوں", chapters: 6, testament: "new" },
  { id: "eph", name: "Ephesians", nameUrdu: "افسیوں", chapters: 6, testament: "new" },
  { id: "php", name: "Philippians", nameUrdu: "فلیپیوں", chapters: 4, testament: "new" },
  { id: "col", name: "Colossians", nameUrdu: "کولسیوں", chapters: 4, testament: "new" },
  { id: "1th", name: "1 Thessalonians", nameUrdu: "1 تھسلونیکیوں", chapters: 5, testament: "new" },
  { id: "2th", name: "2 Thessalonians", nameUrdu: "2 تھسلونیکیوں", chapters: 3, testament: "new" },
  { id: "1ti", name: "1 Timothy", nameUrdu: "1 تیمتھیس", chapters: 6, testament: "new" },
  { id: "2ti", name: "2 Timothy", nameUrdu: "2 تیمتھیس", chapters: 4, testament: "new" },
  { id: "tit", name: "Titus", nameUrdu: "ططس", chapters: 3, testament: "new" },
  { id: "phm", name: "Philemon", nameUrdu: "فلیمون", chapters: 1, testament: "new" },
  { id: "heb", name: "Hebrews", nameUrdu: "عبرانیوں", chapters: 13, testament: "new" },
  { id: "jas", name: "James", nameUrdu: "یعقوب", chapters: 5, testament: "new" },
  { id: "1pe", name: "1 Peter", nameUrdu: "1 پطرس", chapters: 5, testament: "new" },
  { id: "2pe", name: "2 Peter", nameUrdu: "2 پطرس", chapters: 3, testament: "new" },
  { id: "1jn", name: "1 John", nameUrdu: "1 یوحنا", chapters: 5, testament: "new" },
  { id: "2jn", name: "2 John", nameUrdu: "2 یوحنا", chapters: 1, testament: "new" },
  { id: "3jn", name: "3 John", nameUrdu: "3 یوحنا", chapters: 1, testament: "new" },
  { id: "jud", name: "Jude", nameUrdu: "یہوداہ", chapters: 1, testament: "new" },
  { id: "rev", name: "Revelation", nameUrdu: "مکاشفہ", chapters: 22, testament: "new" },
];
