import { Show } from '../types';

export const shows: Show[] = [
  { id: 'debate', title: 'Christian Debate', category: 'Talk Shows', description: 'Engaging discussions on faith and society.', thumbnail: '/images/programs/debate.webp', episode_count: 2, youtube_playlist_id: 'PLC0Rch0KTiEL1XcXiXO76FeMysmOQda-v' },
  { id: 'connection', title: 'Connection', category: 'Talk Shows', description: 'Connecting faith with everyday life.', thumbnail: '/images/programs/connection.webp', episode_count: 21, youtube_playlist_id: 'PLC0Rch0KTiEL-7g_5Zt4nmcj1tKUMVlDJ' },
  { id: '295c', title: '295C', category: 'Social Issues', description: 'Addressing critical social and legal issues.', thumbnail: '/images/programs/295c.webp', episode_count: 64, youtube_playlist_id: 'PLC0Rch0KTiEJty_pIPyX862w551dRhSPC' },
  { id: 'meri-awaz-suno', title: 'Meri Aawaz Suno', category: 'Talk Shows', description: 'A platform for voices that need to be heard.', thumbnail: '/images/programs/meri-awaz-suno.webp', episode_count: 651, youtube_playlist_id: 'PLC0Rch0KTiEL3jSy9_haZ0IwwVnEOM502' },
  { id: 'bol-k-lab-azad', title: 'Bol K Lab Azad Hain Tere', category: 'Talk Shows', description: 'Freedom of expression through faith-based dialogue.', thumbnail: '/images/programs/bol-k-lub-azad-hai-tere.webp', episode_count: 42, youtube_playlist_id: 'PLC0Rch0KTiEJJU9cHbZ_aZHkQuQKtG353' },
  { id: 'ora-et-labora', title: 'Ora et Labora', category: 'Documentary', description: 'Pray and work — faith in action.', thumbnail: '/images/programs/ora-et-labora.webp', episode_count: 18, youtube_playlist_id: 'PLC0Rch0KTiEK78XGqgSzTgYovHc6M6l3M' },
  { id: 'ochtend-met-jezus-douwe', title: 'Ochtend met Jezus | Predikant Douwe Wijmenga', category: 'Devotional', description: 'Morning devotional with Pastor Douwe Wijmenga.', thumbnail: '/images/programs/morning-with-jesus-predikant-douwe-wijmenga.webp', episode_count: 47, youtube_playlist_id: 'PLC0Rch0KTiEJHTsKT-ccjvRsQ7wq0zhNA' },
  { id: 'masihi-zindagi', title: 'Masihi Zindagi', category: 'Devotional', description: 'Christian living guidance and inspiration.', thumbnail: 'https://i.ytimg.com/vi/pX1ngNLVn30/hqdefault.jpg', episode_count: 11, youtube_playlist_id: 'PLC0Rch0KTiEK2HGhHh6ju0UAbR4GPpv_h' },
  { id: 'yesu-sang-sawera-munawar', title: 'Yesu Sang Sawera | Pastor Munawar Virk', category: 'Devotional', description: 'Morning with Jesus devotional.', thumbnail: '/images/programs/yesu-sang-sawera-pastor-munawar-virk.webp', episode_count: 7, youtube_playlist_id: 'PLC0Rch0KTiEJ5atmrt0aNyTJTbBRk8Dtd' },
  { id: 'yesu-sang-sawera-imran', title: 'Yesu Sang Sawera | Pastor Imran Gill', category: 'Devotional', description: 'Morning with Jesus devotional.', thumbnail: '/images/programs/yesu-sang-sawera-pastor-imran-gill.webp', episode_count: 6, youtube_playlist_id: 'PLC0Rch0KTiEK59AdKYUxvjD4FYGGAk-3W' },
  { id: 'yesu-sang-sawera-imko', title: 'Yesu Sang Sawera | Predikant Imko Postma', category: 'Devotional', description: 'Morning with Jesus devotional.', thumbnail: '/images/programs/ochtend-met-jezus-predikant-imko-postma.webp', episode_count: 2, youtube_playlist_id: 'PLC0Rch0KTiEJjSOc-b5azFbgnCgy27PFx' },
  { id: 'yesu-sang-sawera-sarfaraz', title: 'Yesu Sang Sawera | Pastor Sarfaraz Rehmat', category: 'Devotional', description: 'Morning with Jesus devotional.', thumbnail: '/images/programs/yesu-sang-sawera-pastor-sarfaraz-rehmat.webp', episode_count: 56, youtube_playlist_id: 'PLC0Rch0KTiEJIkPavJjvPDX1eslj5q2Mt' },
  { id: 'morning-with-jesus-robert', title: 'Morning With Jesus | Pastor Robert Slack', category: 'Devotional', description: 'Morning devotional with Pastor Robert Slack.', thumbnail: '/images/programs/morning-with-jesus-pastor-robert-slack.webp', episode_count: 39, youtube_playlist_id: 'PLC0Rch0KTiEIR35NdZTLISgKRMlc3BVw3' },
  { id: 'ochtend-met-jezus-terpstra', title: 'Yesu Sang Sawera | Predikant Terpstra', category: 'Devotional', description: 'Morning devotional.', thumbnail: '/images/programs/ochtend-met-jezus-pastor-terpstra.webp', episode_count: 18, youtube_playlist_id: 'PLC0Rch0KTiEKa9nRM45q3IjtjnEcxx8Oq' },
  { id: 'yesu-sang-sawera-parvaiz', title: 'Yesu Sang Sawera | Pastor Parvaiz Iqbal', category: 'Devotional', description: 'Morning with Jesus devotional.', thumbnail: '/images/programs/yesu-sang-sawera-pastor-parvaiz-iqbal.webp', episode_count: 18, youtube_playlist_id: 'PLC0Rch0KTiEI_mnwHqbtFVWkoBepRVJYz' },
  { id: 'yesu-sang-sawera-emmanuel', title: 'Yesu Sang Sawera | Bishop Emmanuel Aftab', category: 'Devotional', description: 'Morning with Jesus devotional.', thumbnail: '/images/programs/yesu-sang-sawera-bishop-emmanuel-aftab.webp', episode_count: 21, youtube_playlist_id: 'PLC0Rch0KTiEIM81Nxga6kBzrWTI4zKW6B' },
  { id: 'puray-dil-se', title: 'Puray Dil Se', category: 'Devotional', description: 'Worship from the heart.', thumbnail: '/images/programs/puray-dil-se.webp', episode_count: 35, youtube_playlist_id: 'PLC0Rch0KTiEJmdYO0rgoAyxHvufDMRqey' },
  { id: 'tehqeeq-e-bible', title: 'Tehqeeq-E-Bible', category: 'Devotional', description: 'Bible research and study.', thumbnail: 'https://i.ytimg.com/vi/-vE4aOXdFU8/hqdefault.jpg', episode_count: 34, youtube_playlist_id: 'PLC0Rch0KTiEJf5LpXqJUB7BOPTIxxYE4Y' },
  { id: 'farman-e-masih', title: 'Farman-e-Masih', category: 'Devotional', description: 'Commandments of Christ.', thumbnail: '/images/programs/farman-e-masih.webp', episode_count: 14, youtube_playlist_id: 'PLC0Rch0KTiEJTLA68BSOZiawjHha_STu6' },
  { id: 'azmat-e-masih', title: 'Azmat-E-Masih', category: 'Devotional', description: 'The greatness of Christ.', thumbnail: 'https://i.ytimg.com/vi/C4Q5lYDdKZg/hqdefault.jpg', episode_count: 11, youtube_playlist_id: 'PLC0Rch0KTiEKieg3BaUFw9Awo951JERSq' },
  { id: 'choti-si-baat', title: 'Choti Si Baat Aam Si Adat', category: 'Talk Shows', description: 'Short yet meaningful conversations.', thumbnail: '/images/programs/choti-si-baat.webp', episode_count: 7, youtube_playlist_id: 'PLC0Rch0KTiELEXZy_VRdLOII3zDpXYh-m' },
  { id: 'aao-hamad-karin', title: 'Aao Hamad Karin', category: 'Devotional', description: 'Come let us praise.', thumbnail: 'https://i.ytimg.com/vi/9JdEOSZFiLs/hqdefault.jpg', episode_count: 29, youtube_playlist_id: 'PLC0Rch0KTiEJD0sPwhLDZKTexs0RhHtTk' },
  { id: 'food-for-your-heart', title: 'Food for Your Heart', category: 'Devotional', description: 'Spiritual nourishment for the soul.', thumbnail: 'https://i.ytimg.com/vi/Ul0WTSmDN2M/hqdefault.jpg', episode_count: 15, youtube_playlist_id: 'PLC0Rch0KTiEKswX3Uhy-Rbc_v8oZGWoaN' },
  { id: 'yesu-sang-sawera-nadeem', title: 'Yesu Sang Sawera | Pastor Nadeem K Dean', category: 'Devotional', description: 'Morning with Jesus devotional.', thumbnail: '/images/programs/yesu-sang-sawera-pastor-nadeem-k-dean.webp', episode_count: 17, youtube_playlist_id: 'PLC0Rch0KTiEJzzhjty0HYs02WBzM4Y7G1' },
  { id: 'daagh', title: 'Daagh', category: 'Drama', description: 'A compelling drama series.', thumbnail: '/images/programs/daag.webp', episode_count: 13, youtube_playlist_id: 'PLC0Rch0KTiEJzd_BEgTrtW25He9bc5ykP' },
  { id: 'meri-kahani', title: 'Meri Kahani', category: 'Drama', description: 'My story — personal journeys of faith.', thumbnail: 'https://i.ytimg.com/vi/_URLEq-amhM/hqdefault.jpg', episode_count: 10, youtube_playlist_id: 'PLC0Rch0KTiEJviSmXh9ffFJ57rLQcS84A' },
  { id: 'bandhan', title: 'Bandhan', category: 'Drama', description: 'Bonds of love and faith.', thumbnail: '/images/programs/bandhan.webp', episode_count: 15, youtube_playlist_id: 'PLC0Rch0KTiEKhqfRdSq7N9syvs31FNUQU' },
  { id: 'aap-ki-sehat', title: 'Aap Ki Sehat', category: 'Health', description: 'Your health — physical and spiritual well-being.', thumbnail: '/images/programs/aap-ki-sehat.webp', episode_count: 29, youtube_playlist_id: 'PLC0Rch0KTiEIez3wRZiuJ3uIAVeqO8UAk' },
  { id: 'return-ticket', title: 'Return Ticket', category: 'Drama', description: 'A journey of return and redemption.', thumbnail: '/images/programs/return-ticket.webp', episode_count: 15, youtube_playlist_id: 'PLC0Rch0KTiEJappsAzGuHckX-6Tnv3e0C' },
  { id: 'aao-chalein', title: 'Aao Chalein', category: 'Documentary', description: 'Let us journey together.', thumbnail: '/images/programs/aao-chalein.webp', episode_count: 226, youtube_playlist_id: 'PLC0Rch0KTiEIXhIrONRD0BUJOfT02hwOZ' },
  { id: 'such-ki-khooj', title: 'Such Ki Khooj', category: 'Documentary', description: 'In search of truth.', thumbnail: 'https://i.ytimg.com/vi/1x6dYFEObWM/hqdefault.jpg', episode_count: 30, youtube_playlist_id: 'PLC0Rch0KTiEJJUdDkkF1ErTjG92L6u4bq' },
  { id: 'safar-e-shanakhat', title: 'Safar-e-Shanakhat', category: 'Documentary', description: 'Journey of discovery.', thumbnail: '/images/programs/safar-e-shanakht.webp', episode_count: 25, youtube_playlist_id: 'PLC0Rch0KTiELmNtPpNsAFdD5R0DuHsc57' },
  { id: 'career-guide', title: 'Career Guide', category: 'Education', description: 'Guidance for career and professional growth.', thumbnail: '/images/programs/career-guide.webp', episode_count: 9, youtube_playlist_id: 'PLC0Rch0KTiEKFnSQS_7_yzCXlBVE14c9K' },
  { id: 'hamare-sitare', title: 'Hamare Sitare', category: 'Talk Shows', description: 'Our stars — celebrating community heroes.', thumbnail: '/images/programs/hamarey-sitarey.webp', episode_count: 51, youtube_playlist_id: 'PLC0Rch0KTiELF-r1NYnvutDhWwFA_PuWb' },
  { id: 'pakistan-hamara-bhi-hai', title: 'Pakistan Hamara Bhi Hai', category: 'Social Issues', description: 'Pakistan belongs to us too.', thumbnail: '/images/programs/pakistan-hamara-bhi-hai.webp', episode_count: 67, youtube_playlist_id: 'PLC0Rch0KTiEL62fRR7QFYnybfId__kUGp' },
  { id: 'btl-drama-specials', title: 'BTL Drama Specials', category: 'Drama', description: 'Special drama productions from BTL TV.', thumbnail: 'https://i.ytimg.com/vi/KF9HGJn_mno/hqdefault.jpg', episode_count: 10, youtube_playlist_id: 'PLC0Rch0KTiEIub8WrDOvvwOfy2VMA8wV2' },
  { id: 'yesu-sang-sawera-william', title: 'Yesu Sang Sawera | Pastor William Paighani', category: 'Devotional', description: 'Morning with Jesus devotional.', thumbnail: 'https://i.ytimg.com/vi/yl1M9TTo0TM/hqdefault.jpg', episode_count: 1, youtube_playlist_id: 'PLC0Rch0KTiEJU6V0fg9XydpOjM8Yp0eAY' },
  { id: 'urdu-bible', title: 'Urdu Bible', category: 'Devotional', description: 'The Holy Bible in Urdu.', thumbnail: 'https://i.ytimg.com/vi/6bjIhLSE504/hqdefault.jpg', episode_count: 80, youtube_playlist_id: 'PLC0Rch0KTiEIXuKgpvm7mq4YlLQ__HssQ' },
  { id: 'prophecies-jesus', title: 'Prophecies About Jesus Christ', category: 'Devotional', description: 'Biblical prophecies about Jesus Christ.', thumbnail: 'https://i.ytimg.com/vi/gf7vSO1Y_G4/hqdefault.jpg', episode_count: 5, youtube_playlist_id: 'PLC0Rch0KTiEINBNsxKVWV5gXlu8EmlWV0' },
  { id: 'kids-programe', title: 'Kids Programe', category: 'Kids', description: 'Fun and educational programs for children.', thumbnail: '/images/programs/kids.webp', episode_count: 20, youtube_playlist_id: 'PLC0Rch0KTiELwlkkreDtcIdxhPmASJbpJ' },
  { id: 'kids-stories', title: 'Kids Stories', category: 'Kids', description: 'Inspiring stories for kids.', thumbnail: '/images/programs/kids.webp', episode_count: 15, youtube_playlist_id: 'PLC0Rch0KTiEJ4Ys17Q2GyDerDxuUkhe2z' },
  { id: 'btl-promos', title: 'BTL TV Promos', category: 'Promos', description: 'Promotional videos from BTL TV.', thumbnail: '/images/programs/promo.webp', episode_count: 5, youtube_playlist_id: 'PLC0Rch0KTiEJ5r54n700_prgbhdZExCJG' },
];

export const categories = ['All', 'Talk Shows', 'Devotional', 'Drama', 'Documentary', 'Social Issues', 'Health', 'Education', 'News', 'Kids'] as const;

export const getShowsByCategory = (category: string) => {
  if (category === 'All') return shows;
  return shows.filter(s => s.category === category);
};
